version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: recipe-book-postgres
    environment:
      POSTGRES_DB: recipe_book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: